In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import urllib3

In [2]:
# SSL 경고 비활성화
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

In [3]:
# 1. 웹페이지 가져오기
url = "https://news.seoul.go.kr/traffic/archives/1551"
response = requests.get(url, verify=False)  # get 메소드 사용 및 SSL 인증서 검증 비활성화
print("문제 1. 웹페이지 가져오기")
print("답: 상태 코드:", response.status_code)  # status_code 속성을 사용하여 상태 코드를 출력합니다.

문제 1. 웹페이지 가져오기
답: 상태 코드: 200

In [5]:
# 2. 모든 테이블 찾기
soup = BeautifulSoup(response.text, 'html.parser')  # HTML 파서를 지정합니다.
tables = soup.select('table')  # 모든 <table> 태그를 찾습니다.
print("\n문제 2. 모든 테이블 찾기")
print(f"답: 찾은 테이블 수: {len(tables)}")  # tables의 길이를 출력합니다.

문제 2. 모든 테이블 찾기
답: 찾은 테이블 수: 3

In [9]:
tables

[<table style="height: 882px;" width="1408">
 <tbody>
 <tr>
 <td rowspan="2">
 <p>구 분</p>
 </td>
 <td rowspan="2">
 <p>계</p>
 </td>
 <td rowspan="2">
 <p>1호선</p>
 </td>
 <td colspan="3">
 <p>2 호 선</p>
 </td>
 <td rowspan="2">
 <p>3호선</p>
 </td>
 <td rowspan="2">
 <p>4호선</p>
 </td>
 <td rowspan="2">
 <p>5호선</p>
 </td>
 <td rowspan="2">
 <p>6호선</p>
 </td>
 <td rowspan="2">
 <p>7호선</p>
 </td>
 <td rowspan="2">
 <p>8호선</p>
 </td>
 <td rowspan="2">
 <p>9호선</p>
 </td>
 <td rowspan="2">
 <p>우이</p>
 <p>신설선</p>
 </td>
 <td rowspan="2">
 <p>신림선</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>순 환</p>
 </td>
 <td colspan="2">
 <p>지 선</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>구 간</p>
 </td>
 <td>
 <p>11개</p>
 </td>
 <td>
 <p>서울역</p>
 <p>~</p>
 <p>청량리</p>
 </td>
 <td>
 <p>성수</p>
 <p>~</p>
 <p>성수</p>
 </td>
 <td>
 <p>신설동</p>
 <p>~</p>
 <p>성수</p>
 </td>
 <td>
 <p>신도림</p>
 <p>~</p>
 <p>까치산</p>
 </td>
 <td>
 <p>지축</p>
 <p>~</p>
 <p>오금</p>
 </td>
 <td>
 <p>당고개</p>
 <p>~</p>
 <p>남태령</p>
 </td>
 <td>
 <p>방화</p>
 <p>~</p>
 <p>하남</p>
 <p>검단산</p>
 <p>/마천</p>
 </td>
 <td>
 <p>응암</p>
 <p>~</p>
 <p>신내</p>
 </td>
 <td>
 <p>장암</p>
 <p>~</p>
 <p>온수</p>
 </td>
 <td>
 <p>암사</p>
 <p>역사</p>
 <p>공원</p>
 <p>~</p>
 <p>모란</p>
 </td>
 <td>
 <p>개화</p>
 <p>~</p>
 <p>중앙</p>
 <p>보훈</p>
 <p>병원</p>
 </td>
 <td>
 <p>북한산</p>
 <p>우이</p>
 <p>~</p>
 <p>신설동</p>
 </td>
 <td>
 <p>샛강</p>
 <p>~</p>
 <p>관악산</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>영업거리</p>
 <p>(km)</p>
 </td>
 <td>
 <p>359.</p>
 <p>86</p>
 </td>
 <td>
 <p>7.8</p>
 </td>
 <td>
 <p>48.8</p>
 </td>
 <td>
 <p>5.4</p>
 </td>
 <td>
 <p>6</p>
 </td>
 <td>
 <p>38.2</p>
 </td>
 <td>
 <p>31.7</p>
 </td>
 <td>
 <p>59.8</p>
 </td>
 <td>
 <p>36.3</p>
 </td>
 <td>
 <p>46.9</p>
 </td>
 <td>
 <p>19.2</p>
 </td>
 <td>
 <p>40.6</p>
 </td>
 <td>
 <p>11.4</p>
 </td>
 <td>
 <p>7.76</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>역 수</p>
 </td>
 <td>
 <p>338</p>
 </td>
 <td>
 <p>10</p>
 </td>
 <td>
 <p>43</p>
 </td>
 <td>
 <p>4</p>
 </td>
 <td>
 <p>3</p>
 </td>
 <td>
 <p>34</p>
 </td>
 <td>
 <p>26</p>
 </td>
 <td>
 <p>56</p>
 </td>
 <td>
 <p>39</p>
 </td>
 <td>
 <p>42</p>
 </td>
 <td>
 <p>19</p>
 </td>
 <td>
 <p>38</p>
 </td>
 <td>
 <p>13</p>
 </td>
 <td>
 <p>11</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>소요시간</p>
 <p>(분)</p>
 </td>
 <td>
 <p>9</p>
 <p>~</p>
 <p>109.5</p>
 </td>
 <td>
 <p>18</p>
 </td>
 <td>
 <p>90</p>
 </td>
 <td>
 <p>9</p>
 </td>
 <td>
 <p>11</p>
 </td>
 <td>
 <p>67.5</p>
 </td>
 <td>
 <p>53</p>
 </td>
 <td>
 <p>109.5</p>
 </td>
 <td>
 <p>73.8</p>
 </td>
 <td>
 <p>87</p>
 </td>
 <td>
 <p>51.5</p>
 </td>
 <td>
 <p>79.8</p>
 <p>(일반)</p>
 <p>52.5</p>
 <p>(급행)</p>
 </td>
 <td>
 <p>23</p>
 </td>
 <td>
 <p>18.1</p>
 </td>
 </tr>
 <tr>
 <td rowspan="2">
 <p>운행시격</p>
 <p>(분)</p>
 </td>
 <td>
 <p>RH</p>
 </td>
 <td>
 <p>3.0</p>
 </td>
 <td>
 <p>2.5</p>
 </td>
 <td>
 <p>7.0</p>
 </td>
 <td>
 <p>10.0</p>
 </td>
 <td>
 <p>3.0</p>
 </td>
 <td>
 <p>2.5</p>
 </td>
 <td>
 <p>2.5</p>
 </td>
 <td>
 <p>4.0</p>
 </td>
 <td>
 <p>2.5</p>
 </td>
 <td>
 <p>4.5</p>
 </td>
 <td>
 <p>3.1</p>
 </td>
 <td>
 <p>2.9</p>
 </td>
 <td>
 <p>4</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>NH</p>
 </td>
 <td>
 <p>5.0</p>
 </td>
 <td>
 <p>5.5</p>
 </td>
 <td>
 <p>10.0</p>
 </td>
 <td>
 <p>10.0</p>
 </td>
 <td>
 <p>6.5</p>
 </td>
 <td>
 <p>5.5</p>
 </td>
 <td>
 <p>6.5</p>
 </td>
 <td>
 <p>8.0</p>
 </td>
 <td>
 <p>6.0</p>
 </td>
 <td>
 <p>8.0</p>
 </td>
 <td>
 <p>5.5</p>
 </td>
 <td>
 <p>4~12</p>
 </td>
 <td>
 <p>4~10</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>평일 운행횟수</p>
 </td>
 <td>
 <p>5,347</p>
 </td>
 <td>
 <p>588</p>
 </td>
 <td>
 <p>528</p>
 </td>
 <td>
 <p>226</p>
 </td>
 <td>
 <p>220</p>
 </td>
 <td>
 <p>406</p>
 </td>
 <td>
 <p>487</p>
 </td>
 <td>
 <p>430</p>
 </td>
 <td>
 <p>340</p>
 </td>
 <td>
 <p>406</p>
 </td>
 <td>
 <p>324</p>
 </td>
 <td>
 <p>492</p>
 </td>
 <td>
 <p>516</p>
 </td>
 <td>
 <p>384</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>열차 편성수</p>
 </td>
 <td>
 <p>504</p>
 </td>
 <td>
 <p>16</p>
 </td>
 <td>
 <p>75</p>
 </td>
 <td>
 <p>5</p>
 </td>
 <td>
 <p>4</p>
 </td>
 <td>
 <p>49</p>
 </td>
 <td>
 <p>52</p>
 </td>
 <td>
 <p>80</p>
 </td>
 <td>
 <p>39</p>
 </td>
 <td>
 <p>72</p>
 </td>
 <td>
 <p>29</p>
 </td>
 <td>
 <p>53</p>
 </td>
 <td>
 <p>18</p>
 </td>
 <td>
 <p>12</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>전동차수</p>
 <p>(칸)</p>
 </td>
 <td>
 <p>4,057</p>
 </td>
 <td>
 <p>160</p>
 </td>
 <td>
 <p>750</p>
 </td>
 <td>
 <p>20</p>
 </td>
 <td>
 <p>24</p>
 </td>
 <td>
 <p>490</p>
 </td>
 <td>
 <p>520</p>
 </td>
 <td>
 <p>640</p>
 </td>
 <td>
 <p>312</p>
 </td>
 <td>
 <p>577</p>
 </td>
 <td>
 <p>174</p>
 </td>
 <td>
 <p>318</p>
 </td>
 <td>
 <p>36</p>
 </td>
 <td>
 <p>36</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>RH 혼잡도</p>
 <p>(%)</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>124.4</td>
 <td>
 <p>154.6</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>138.8</p>
 </td>
 <td>
 <p>142.3</p>
 </td>
 <td>
 <p>131.2</p>
 </td>
 <td>
 <p>109.9</p>
 </td>
 <td>
 <p>140.7</p>
 </td>
 <td>
 <p>148.6</p>
 </td>
 <td>
 <p>177.7</p>
 </td>
 <td>
 <p>142.3</p>
 </td>
 <td>
 <p>160.5</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>조성칸수</p>
 <p>(칸)</p>
 </td>
 <td>
 <p>91</p>
 </td>
 <td>
 <p>10</p>
 </td>
 <td>
 <p>10</p>
 </td>
 <td>
 <p>4</p>
 </td>
 <td>
 <p>6</p>
 </td>
 <td>
 <p>10</p>
 </td>
 <td>
 <p>10</p>
 </td>
 <td>
 <p>8</p>
 </td>
 <td>
 <p>8</p>
 </td>
 <td>
 <p>8</p>
 </td>
 <td>
 <p>6</p>
 </td>
 <td>
 <p>6</p>
 </td>
 <td>
 <p>2</p>
 </td>
 <td>
 <p>3</p>
 </td>
 </tr>
 </tbody>
 </table>,
 <table>
 <tbody>
 <tr>
 <td colspan="2" rowspan="2">
 <p>구 분</p>
 </td>
 <td rowspan="2">
 <p>계</p>
 </td>
 <td rowspan="2">
 <p>1호선</p>
 </td>
 <td rowspan="2">
 <p>2호선</p>
 </td>
 <td rowspan="2">
 <p>3호선</p>
 </td>
 <td rowspan="2">
 <p>4호선</p>
 </td>
 <td rowspan="2">
 <p>5호선</p>
 </td>
 <td rowspan="2">
 <p>6호선</p>
 </td>
 <td rowspan="2">
 <p>7호선</p>
 </td>
 <td rowspan="2">
 <p>8호선</p>
 </td>
 <td colspan="2">
 <p>9호선</p>
 </td>
 <td rowspan="2">
 <p>우이</p>
 <p>신설</p>
 </td>
 <td rowspan="2">
 <p>신림</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>1단계</p>
 </td>
 <td>
 <p>2·3단계</p>
 </td>
 </tr>
 <tr>
 <td rowspan="3">
 <p>운송</p>
 <p>인원</p>
 <p>(천명/일)</p>
 </td>
 <td>
 <p>’25.1월말</p>
 <p>(A)</p>
 </td>
 <td>
 <p>7,315</p>
 </td>
 <td>405</td>
 <td>1,964</td>
 <td>813</td>
 <td>791</td>
 <td>945</td>
 <td>522</td>
 <td>853</td>
 <td>312</td>
 <td>428</td>
 <td>
 <p>147</p>
 </td>
 <td>
 <p>65</p>
 </td>
 <td>
 <p>70</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>’24.1월말</p>
 <p>(B)</p>
 </td>
 <td>
 <p>7,210</p>
 </td>
 <td>396</td>
 <td>1,921</td>
 <td>796</td>
 <td>765</td>
 <td>917</td>
 <td>510</td>
 <td>845</td>
 <td>292</td>
 <td>464</td>
 <td>
 <p>158</p>
 </td>
 <td>
 <p>71</p>
 </td>
 <td>
 <p>75</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>A/B(%)</p>
 </td>
 <td>
 <p> </p>
 </td>
 <td>
 <p>103%</p>
 </td>
 <td>
 <p>102%</p>
 </td>
 <td>
 <p>102%</p>
 </td>
 <td>
 <p>103%</p>
 </td>
 <td>
 <p>103%</p>
 </td>
 <td>
 <p>102%</p>
 </td>
 <td>
 <p>101%</p>
 </td>
 <td>
 <p>107%</p>
 </td>
 <td>
 <p>92%</p>
 </td>
 <td>
 <p>93%</p>
 </td>
 <td>
 <p>92%</p>
 </td>
 <td>
 <p>93%</p>
 </td>
 </tr>
 <tr>
 <td rowspan="3">
 <p>운수</p>
 <p>수입금</p>
 <p>(백만원/일)</p>
 </td>
 <td>
 <p>’25.1월말</p>
 <p>(A)</p>
 </td>
 <td>
 <p>4,752</p>
 </td>
 <td>219</td>
 <td>1,420</td>
 <td>509</td>
 <td>491</td>
 <td>597</td>
 <td>323</td>
 <td>563</td>
 <td>190</td>
 <td>268</td>
 <td>104</td>
 <td>31</td>
 <td>
 <p>37</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>’24.1월말</p>
 <p>(B)</p>
 </td>
 <td>
 <p>4,508</p>
 </td>
 <td>203</td>
 <td>1,329</td>
 <td>477</td>
 <td>455</td>
 <td>559</td>
 <td>303</td>
 <td>538</td>
 <td>171</td>
 <td>294</td>
 <td>105</td>
 <td>34</td>
 <td>
 <p>40</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>A/B(%)</p>
 </td>
 <td>
 <p> </p>
 </td>
 <td>
 <p>108%</p>
 </td>
 <td>
 <p>107%</p>
 </td>
 <td>
 <p>107%</p>
 </td>
 <td>
 <p>108%</p>
 </td>
 <td>
 <p>107%</p>
 </td>
 <td>
 <p>107%</p>
 </td>
 <td>
 <p>104%</p>
 </td>
 <td>
 <p>111%</p>
 </td>
 <td>
 <p>91%</p>
 </td>
 <td>
 <p>99%</p>
 </td>
 <td>
 <p>91%</p>
 </td>
 <td>
 <p>93%</p>
 </td>
 </tr>
 </tbody>
 </table>,
 <table>
 <tbody>
 <tr>
 <td colspan="2" rowspan="2">
 <p>구 분</p>
 </td>
 <td colspan="2">
 <p>계</p>
 </td>
 <td colspan="2">
 <p>엘리베이터</p>
 </td>
 <td colspan="2">
 <p>에스컬레이터</p>
 </td>
 <td colspan="2">
 <p>휠체어 리프트</p>
 </td>
 <td colspan="2">
 <p>무빙워크</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>역수</p>
 </td>
 <td>
 <p>대</p>
 </td>
 <td>
 <p>역수</p>
 </td>
 <td>
 <p>대</p>
 </td>
 <td>
 <p>역수</p>
 </td>
 <td>
 <p>대</p>
 </td>
 <td>
 <p>역수</p>
 </td>
 <td>
 <p>대</p>
 </td>
 <td>
 <p>역수</p>
 </td>
 <td>
 <p>대</p>
 </td>
 </tr>
 <tr>
 <td colspan="2">
 <p>계</p>
 </td>
 <td>
 <p>338</p>
 </td>
 <td>
 <p>3,888</p>
 </td>
 <td>
 <p>338</p>
 </td>
 <td>
 <p>1,105</p>
 </td>
 <td>
 <p>318</p>
 </td>
 <td>
 <p>2,681</p>
 </td>
 <td>
 <p>32</p>
 </td>
 <td>
 <p>70</p>
 </td>
 <td>
 <p>8</p>
 </td>
 <td>
 <p>24</p>
 </td>
 </tr>
 <tr>
 <td colspan="2">
 <p>1~4호선</p>
 </td>
 <td>
 <p>120</p>
 </td>
 <td>
 <p>1,016</p>
 </td>
 <td>
 <p>120</p>
 </td>
 <td>
 <p>365</p>
 </td>
 <td>
 <p>107</p>
 </td>
 <td>
 <p>630</p>
 </td>
 <td>
 <p>7</p>
 </td>
 <td>
 <p>14</p>
 </td>
 <td>
 <p>1</p>
 </td>
 <td>
 <p>2</p>
 </td>
 </tr>
 <tr>
 <td colspan="2">
 <p>5~8호선</p>
 </td>
 <td>
 <p>156</p>
 </td>
 <td>
 <p>1,811</p>
 </td>
 <td>
 <p>156</p>
 </td>
 <td>
 <p>497</p>
 </td>
 <td>
 <p>149</p>
 </td>
 <td>
 <p>1,241</p>
 </td>
 <td>
 <p>25</p>
 </td>
 <td>
 <p>56</p>
 </td>
 <td>
 <p>5</p>
 </td>
 <td>
 <p>16</p>
 </td>
 </tr>
 <tr>
 <td rowspan="2">
 <p>9호선</p>
 </td>
 <td>
 <p>1단계</p>
 </td>
 <td>
 <p>25</p>
 </td>
 <td>
 <p>574</p>
 </td>
 <td>
 <p>25</p>
 </td>
 <td>
 <p>101</p>
 </td>
 <td>
 <p>25</p>
 </td>
 <td>
 <p>465</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>2</p>
 </td>
 <td>
 <p>6</p>
 </td>
 </tr>
 <tr>
 <td>
 <p>2,3단계</p>
 </td>
 <td>
 <p>13</p>
 </td>
 <td>
 <p>256</p>
 </td>
 <td>
 <p>13</p>
 </td>
 <td>
 <p>55</p>
 </td>
 <td>
 <p>13</p>
 </td>
 <td>
 <p>201</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 </tr>
 <tr>
 <td colspan="2">
 <p>우이신설선</p>
 </td>
 <td>
 <p>13</p>
 </td>
 <td>
 <p>126</p>
 </td>
 <td>
 <p>13</p>
 </td>
 <td>
 <p>52</p>
 </td>
 <td>
 <p>13</p>
 </td>
 <td>
 <p>74</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 </tr>
 <tr>
 <td colspan="2">
 <p>신림선</p>
 </td>
 <td>
 <p>11</p>
 </td>
 <td>
 <p>105</p>
 </td>
 <td>
 <p>11</p>
 </td>
 <td>
 <p>35</p>
 </td>
 <td>
 <p>11</p>
 </td>
 <td>
 <p>70</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 <td>
 <p>-</p>
 </td>
 </tr>
 </tbody>
 </table>]

In [ ]:
# 3. 각 테이블 처리
subway_data = {}
for i, table in enumerate(tables):
    title = table.find_previous_sibling('h5')  # 테이블 앞의 <h5> 태그를 찾습니다.
    table_name = title.get_text().strip() if title else f"Table {i + 1}"  # 테이블 이름을 설정합니다.

    data = [[td.get_text().strip() for td in tr.select('th, td')] for tr in table.select('tr')]  # 테이블의 모든 셀 내용을 추출합니다.
    max_cols = max(len(row) for row in data)  # 가장 긴 행의 길이를 찾습니다.
    data = [row + [''] * (max_cols - len(row)) for row in data]  # 모든 행의 길이를 동일하게 맞춥니다.

    df = pd.DataFrame(data[1:], columns=data[0])  # DataFrame을 생성합니다.
    subway_data[table_name] = df

print("\n문제 3. 테이블 데이터 추출 및 DataFrame 생성")
print(f"답: 처리된 테이블 수: {len(subway_data)}")  # 처리된 테이블의 수를 출력합니다.

문제 3. 테이블 데이터 추출 및 DataFrame 생성
답: 처리된 테이블 수: 3

In [17]:
# 4. 결과 출력
print("\n문제 4. 각 테이블의 요약 정보 출력")
for name, df in subway_data.items():  # 각 테이블에 대해 반복합니다.
    print(f"\n테이블 이름: {name}")
    print("답: 처음 5개 행")
    print(df.head())  # 각 DataFrame의 처음 5개 행을 출력합니다.
    print("\n" + "=" * 50)

문제 4. 각 테이블의 요약 정보 출력

테이블 이름:
답: 처음 5개 행
          구 분            계          1호선      2 호 선         3호선          4호선  \
0         순 환          지 선
1         구 간          11개  서울역\n~\n청량리  성수\n~\n성수  신설동\n~\n성수  신도림\n~\n까치산
2  영업거리\n(km)     359.\n86          7.8       48.8         5.4            6
3         역 수          338           10         43           4            3
4   소요시간\n(분)  9\n~\n109.5           18         90           9           11

         5호선          6호선                  7호선        8호선        9호선  \
0
1  지축\n~\n오금  당고개\n~\n남태령  방화\n~\n하남\n검단산\n/마천  응암\n~\n신내  장암\n~\n온수
2       38.2         31.7                 59.8       36.3       46.9
3         34           26                   56         39         42
4       67.5           53                109.5       73.8         87

             우이\n신설선                     신림선
0
1  암사\n역사\n공원\n~\n모란       개화\n~\n중앙\n보훈\n병원  북한산\n우이\n~\n신설동  샛강\n~\n관악산
2               19.2                    40.6             11.4        7.76
3                 19                      38               13          11
4               51.5  79.8\n(일반)\n52.5\n(급행)               23        18.1

==================================================

테이블 이름: □ 노선별 운송실적
답: 처음 5개 행
                구 분             계    1호선    2호선    3호선   4호선   5호선   6호선  \
0               1단계         2·3단계
1    운송\n인원\n(천명/일)  ’25.1월말\n(A)  7,315    405  1,964   813   791   945
2      ’24.1월말\n(B)         7,210    396  1,921    796   765   917   510
3            A/B(%)                 103%   102%   102%  103%  103%  102%
4  운수\n수입금\n(백만원/일)  ’25.1월말\n(A)  4,752    219  1,420   509   491   597

    7호선   8호선  9호선 우이\n신설   신림
0
1   522   853  312    428  147   65  70
2   845   292  464    158   71   75
3  101%  107%  92%    93%  92%  93%
4   323   563  190    268  104   31  37

==================================================

테이블 이름: □ 지하철 장애인 편의시설 설치현황
답: 처음 5개 행
     구 분    계  엘리베이터 에스컬레이터 휠체어 리프트 무빙워크
0     역수    대     역수      대      역수    대     역수    대  역수  대
1      계  338  3,888    338   1,105  318  2,681   32  70  8  24
2  1~4호선  120  1,016    120     365  107    630    7  14  1   2
3  5~8호선  156  1,811    156     497  149  1,241   25  56  5  16
4    9호선  1단계     25    574      25  101     25  465   -  -   2  6

==================================================

In [18]:
# 5. 첫 번째 테이블에서 노선별 정보 추출
print("\n문제 5. 첫 번째 테이블에서 노선별 정보 추출")
if subway_data:
    first_table_name = list(subway_data.keys())[0]  # 첫 번째 테이블의 이름을 가져옵니다.
    operation_data = subway_data[first_table_name]  # 첫 번째 테이블의 데이터를 가져옵니다.

    print("답: 노선별 정보")
    for _, row in operation_data.iterrows():  # 각 행에 대해 반복합니다.
        if row.iloc[0] and row.iloc[0] != '구 분':  # 첫 번째 열이 비어있지 않고 '구 분'이 아닌 경우
            print(f"\n{row.iloc[0]}:")  # 노선 이름을 출력합니다.
            for col, val in row.items():  # 각 열에 대해 반복합니다.
                if col != row.iloc[0] and val:  # 첫 번째 열이 아니고 값이 있는 경우
                    print(f"  {col}: {val}")  # 열 이름과 값을 출력합니다.

문제 5. 첫 번째 테이블에서 노선별 정보 추출
답: 노선별 정보

순 환:
  구 분: 순 환
  계: 지 선

구 간:
  구 분: 구 간
  계: 11개
  1호선: 서울역
~
청량리
  2 호 선: 성수
~
성수
  3호선: 신설동
~
성수
  4호선: 신도림
~
까치산
  5호선: 지축
~
오금
  6호선: 당고개
~
남태령
  7호선: 방화
~
하남
검단산
/마천
  8호선: 응암
~
신내
  9호선: 장암
~
온수
  우이
신설선: 암사
역사
공원
~
모란
  신림선: 개화
~
중앙
보훈
병원
  : 북한산
우이
~
신설동
  : 샛강
~
관악산

영업거리
(km):
  구 분: 영업거리
(km)
  계: 359.
86
  1호선: 7.8
  2 호 선: 48.8
  3호선: 5.4
  4호선: 6
  5호선: 38.2
  6호선: 31.7
  7호선: 59.8
  8호선: 36.3
  9호선: 46.9
  우이
신설선: 19.2
  신림선: 40.6
  : 11.4
  : 7.76

역 수:
  구 분: 역 수
  계: 338
  1호선: 10
  2 호 선: 43
  3호선: 4
  4호선: 3
  5호선: 34
  6호선: 26
  7호선: 56
  8호선: 39
  9호선: 42
  우이
신설선: 19
  신림선: 38
  : 13
  : 11

소요시간
(분):
  구 분: 소요시간
(분)
  계: 9
~
109.5
  1호선: 18
  2 호 선: 90
  3호선: 9
  4호선: 11
  5호선: 67.5
  6호선: 53
  7호선: 109.5
  8호선: 73.8
  9호선: 87
  우이
신설선: 51.5
  신림선: 79.8
(일반)
52.5
(급행)
  : 23
  : 18.1

운행시격
(분):
  구 분: 운행시격
(분)
  계: RH
  1호선: 3.0
  2 호 선: 2.5
  3호선: 7.0
  4호선: 10.0
  5호선: 3.0
  6호선: 2.5
  7호선: 2.5
  8호선: 4.0
  9호선: 2.5
  우이
신설선: 4.5
  신림선: 3.1
  : 2.9
  : 4

NH:
  구 분: NH
  계: 5.0
  1호선: 5.5
  2 호 선: 10.0
  3호선: 10.0
  4호선: 6.5
  5호선: 5.5
  6호선: 6.5
  7호선: 8.0
  8호선: 6.0
  9호선: 8.0
  우이
신설선: 5.5
  신림선: 4~12
  : 4~10

평일 운행횟수:
  구 분: 평일 운행횟수
  계: 5,347
  1호선: 588
  2 호 선: 528
  3호선: 226
  4호선: 220
  5호선: 406
  6호선: 487
  7호선: 430
  8호선: 340
  9호선: 406
  우이
신설선: 324
  신림선: 492
  : 516
  : 384

열차 편성수:
  구 분: 열차 편성수
  계: 504
  1호선: 16
  2 호 선: 75
  3호선: 5
  4호선: 4
  5호선: 49
  6호선: 52
  7호선: 80
  8호선: 39
  9호선: 72
  우이
신설선: 29
  신림선: 53
  : 18
  : 12

전동차수
(칸):
  구 분: 전동차수
(칸)
  계: 4,057
  1호선: 160
  2 호 선: 750
  3호선: 20
  4호선: 24
  5호선: 490
  6호선: 520
  7호선: 640
  8호선: 312
  9호선: 577
  우이
신설선: 174
  신림선: 318
  : 36
  : 36

RH 혼잡도
(%):
  구 분: RH 혼잡도
(%)
  계: -
  1호선: 124.4
  2 호 선: 154.6
  3호선: -
  4호선: -
  5호선: 138.8
  6호선: 142.3
  7호선: 131.2
  8호선: 109.9
  9호선: 140.7
  우이
신설선: 148.6
  신림선: 177.7
  : 142.3
  : 160.5

조성칸수
(칸):
  구 분: 조성칸수
(칸)
  계: 91
  1호선: 10
  2 호 선: 10
  3호선: 4
  4호선: 6
  5호선: 10
  6호선: 10
  7호선: 8
  8호선: 8
  9호선: 8
  우이
신설선: 6
  신림선: 6
  : 2
  : 3